### ISSUE TITLE
Etherpad not able to start

### ISSUE THREAD

**Issue by gr41n** [capesstack/capes-docker#29]
I'm still investigating on my end, but I haven't been able to get the etherpad container to start. The logs show it failing when it tries to connect to the database container: 

`ERROR 1045 (28000): Access denied for user 'etherpad'@'172.18.0.7' (using password: YES)
ERROR 1045 (28000): Access denied for user 'etherpad'@'172.18.0.7' (using password: YES)`

The mysql container has an IP of x.x.x.2, but the log shows it going to .7, so I believe that this could be the issue. 

It was working at one time - I'm not yet sure sure why it started to fail. I reran the deploy script after wiping out the network and containers but same issue. 

I also looked into the password to make sure that they were both matching...

On the etherpad container:
```
            "Env": [
                "ETHERPAD_TITLE=CAPES",
                "ETHERPAD_PORT=9001",
                "ETHERPAD_ADMIN_PASSWORD=MmQ4ZTA4OWZkOWE3ZjMzNzQ5NzhiZGY1",
                "ETHERPAD_ADMIN_USER=admin",
                "ETHERPAD_DB_TYPE=mysql",
                "ETHERPAD_DB_HOST=capes-etherpad-mysql",
                "ETHERPAD_DB_USER=etherpad",
                "ETHERPAD_DB_PASSWORD=ODFjMzAwYTdkZDkzOWNiNTZhY2VmY2Y1",
                "ETHERPAD_DB_NAME=etherpad",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=9.11.1",
                "YARN_VERSION=1.5.1",
                "ETHERPAD_VERSION=1.6.5",
                "NODE_ENV=production"
            ],
```

Docker Inspect on the mysql container:

```
                "MYSQL_DATABASE=etherpad",
                "MYSQL_USER=etherpad",
                "MYSQL_PASSWORD=ODFjMzAwYTdkZDkzOWNiNTZhY2VmY2Y1",
                "MYSQL_RANDOM_ROOT_PASSWORD=yes",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "MYSQL_MAJOR=5.7",
                "MYSQL_VERSION=5.7.26-1debian9"
```

Could be PEBCAK! I'll keep exploring.

**Comment by gr41n** [comment]
Rebuilt from scratch w/o issues. There must have been PEBCAK somewhere...I made a lot of modifications to the deploy script, and I also admined etherpad directly. I'm wondering if it was as stupid as me changing the db pass in etherpad when I meant to change the admin pass.

Sorry for the unnecessary issue. Feel free to delete this!

**Comment by peasead** [comment]
Not a problem. That's what an open source project is all about!

I do appreciate you following up.
