### ISSUE TITLE
CentOS Linux release 8.2.2004 (Core)  - Cyberchef installation issue

### ISSUE THREAD

**Issue by pan0707** [capesstack/capes-docker#54]
I am trying to install Cyberchef on Centos linux version 8 but it gives following error.

#grunt prod --force

Warning:  Used --force, continuing.

Running "copy:standalone" (copy) task
Verifying property copy.standalone exists in config...ERROR
>> Unable to process task.
Warning: Required config property "copy.standalone" missing. Used --force, continuing.

Running "zip:standalone" (zip) task
Verifying property zip.standalone exists in config...ERROR
>> Unable to process task.
Warning: Required config property "zip.standalone" missing. Used --force, continuing.

Running "clean:standalone" (clean) task
Verifying property clean.standalone exists in config...ERROR
>> Unable to process task.
Warning: Required config property "clean.standalone" missing. Used --force, continuing.
>> No "chmod" targets found.
Warning: Task "chmod" failed. Used --force, continuing.

Done, but with warnings.

**Comment by peasead** [comment]
Thanks for the Issue. 

Per the documentation, the requirement is for CentOS 7. It says `7.6 (Core)`, but it's been implanted on any version 7.6-7.8. 

https://github.com/capesstack/capes-docs#requirements

There are **substantial** changes for CentOS 8. Namely the way containers (Podman) are implemented. 

If you do a conversion, I'd be more than a happy to merge it with a PR.

**Comment by pan0707** [comment]
Hi Thanks for reply but could please let me know the proper steps to implement the cyberchef in centos 8. As still i am facing the issue. 

Appreciating your feedback.

**Comment by peasead** [comment]
As I stated, CentOS 8 **is not supported** for CAPES. 

You'll have to check with the [CyberChef](https://github.com/gchq/CyberChef) project on how to use CentOS 8.
