### ISSUE TITLE
remnux hubspot no longer hosting cyberchef

### ISSUE THREAD

**Issue by guirkgumbo** [capesstack/capes-docker#60]
**Describe the bug**
remnux hubspot no longer hosting cyberchef

**To Reproduce**
https://hub.docker.com/u/remnux
Running the sudo sh deploy_capes.sh errors out during cyberchef pull

**Comment by peasead** [comment]
Thanks for opening the issue, @guirkgumbo 

`deploy_capes.sh` has been pulling from `mpepping/cyberchef` for a while. Are you using the right version of the deploy script? It was changed here https://github.com/capesstack/capes-docker/commit/a39cd09eed67043576dadbd013626edf50ad1754?

```
# Cyberchef Service
docker run -d --network capes --restart unless-stopped \
 --name capes-cyberchef mpepping/cyberchef:${cyberchef_ver}
```

**Comment by guirkgumbo** [comment]
Whoops. My fault. Thanks for responding @peasead !
